name: position_dex_sdk
description: SDK for dex 2.0 position exchange.
version: 1.1.3
homepage: https://github.com/PositionExchange/position_dex_sdk_mobile

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  decimal: ^2.3.0
  ethereum_addresses: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.21.0


flutter:
  module:
    androidX: true
    androidPackage: com.position.dex.sdk.project
    iosBundleIdentifier: com.position.dex.sdk.project


